http:
  host: "0.0.0.0"
  port: "8080"

pg:
  host: "postgres-order"
  port: "5432"
  database: "order"
  user: "order_admin"
  password: "order_secret"
  sslmode: "disable"

inventory_client:
  address: "inventory-service:50051"

payment_client:
  address: "payment-service:50052"

iam_client:
  address: "iam-service:50053"

logger:
  level: "info"

kafka:
  brokers:
    - "kafka:29092"

order_paid_producer:
  topic: "order.paid"

ship_assembled_consumer:
  topic: "assembly.ship-assembled"
  group_id: "order-service"

otel:
  endpoint: "otel-collector:4317"
  service_name: "order-service"

rate_limit:
  redis_address: "redis-ratelimit:6379"
  rate: 100
  burst: 200
