syntax = "proto3";

package payment.v1;

import "buf/validate/validate.proto";
import "google/api/annotations.proto";
import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";

option go_package = "github.com/mbakhodurov/homeworks2/week4/shared/pkg/proto/payment/v1;payment_v1";

// PaymentService обрабатывает оплату заказов
service PaymentService {
  // PayOrder обрабатывает оплату заказа
  rpc PayOrder(PayOrderRequest) returns (PayOrderResponse) {
    option (google.api.http) = {
      post: "/api/v1/payment/pay_order"
      body: "*"
    };
  }
}

// Способ оплаты
enum PaymentMethod {
  PAYMENT_METHOD_UNSPECIFIED = 0; // неизвестный способ
  PAYMENT_METHOD_CARD = 1; // банковская карта
  PAYMENT_METHOD_SBP = 2; // система быстрых платежей
  PAYMENT_METHOD_CREDIT_CARD = 3; // кредитная карта
  PAYMENT_METHOD_INVESTOR_MONEY = 4; // деньги инвестора (внутренний метод)
}

// Запрос на оплату заказа
message PayOrderRequest {
  // UUID заказа
  string order_uuid = 1 [(buf.validate.field).string = {
    min_len: 10
    max_len: 50
  }];

  string user_uuid = 2 [(buf.validate.field).string = {
    min_len: 10
    max_len: 50
  }]; // UUID пользователя, который инициирует оплату
  PaymentMethod payment_method = 3; // выбранный способ оплаты
}

// Ответ на оплату заказа
message PayOrderResponse {
  string transaction_uuid = 1; // UUID транзакции оплаты
}
