grpc:
  host: "0.0.0.0"
  port: "50053"

http:
  host: ""
  port: "8084"

postgres:
  host: "postgres-iam"
  port: "5432"
  database: "iam-service"
  user: "iam-service-user"
  password: "iam-service-password"
  sslmode: "disable"

redis:
  host: "redis-iam"
  port: "6379"
  password: ""
  db: 0
  connection_timeout: 5s

session:
  ttl: 24h

logger:
  level: "info"

otel:
  endpoint: "otel-collector:4317"
  service_name: "iam-service"
