// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: inventory/v1/inventory.proto

package inventory_v1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PartType тип детали космического корабля
type PartType int32

const (
	// PART_TYPE_UNSPECIFIED не указан
	PartType_PART_TYPE_UNSPECIFIED PartType = 0
	// PART_TYPE_HULL корпус корабля
	PartType_PART_TYPE_HULL PartType = 1
	// PART_TYPE_ENGINE двигатель
	PartType_PART_TYPE_ENGINE PartType = 2
	// PART_TYPE_SHIELD защитный щит
	PartType_PART_TYPE_SHIELD PartType = 3
	// PART_TYPE_WEAPON вооружение
	PartType_PART_TYPE_WEAPON PartType = 4
)

// Enum value maps for PartType.
var (
	PartType_name = map[int32]string{
		0: "PART_TYPE_UNSPECIFIED",
		1: "PART_TYPE_HULL",
		2: "PART_TYPE_ENGINE",
		3: "PART_TYPE_SHIELD",
		4: "PART_TYPE_WEAPON",
	}
	PartType_value = map[string]int32{
		"PART_TYPE_UNSPECIFIED": 0,
		"PART_TYPE_HULL":        1,
		"PART_TYPE_ENGINE":      2,
		"PART_TYPE_SHIELD":      3,
		"PART_TYPE_WEAPON":      4,
	}
)

func (x PartType) Enum() *PartType {
	p := new(PartType)
	*p = x
	return p
}

func (x PartType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PartType) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_v1_inventory_proto_enumTypes[0].Descriptor()
}

func (PartType) Type() protoreflect.EnumType {
	return &file_inventory_v1_inventory_proto_enumTypes[0]
}

func (x PartType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PartType.Descriptor instead.
func (PartType) EnumDescriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

// EngineClass класс двигателя
type EngineClass int32

const (
	// ENGINE_CLASS_UNSPECIFIED не указан
	EngineClass_ENGINE_CLASS_UNSPECIFIED EngineClass = 0
	// ENGINE_CLASS_A класс A
	EngineClass_ENGINE_CLASS_A EngineClass = 1
	// ENGINE_CLASS_B класс B
	EngineClass_ENGINE_CLASS_B EngineClass = 2
	// ENGINE_CLASS_C класс C
	EngineClass_ENGINE_CLASS_C EngineClass = 3
)

// Enum value maps for EngineClass.
var (
	EngineClass_name = map[int32]string{
		0: "ENGINE_CLASS_UNSPECIFIED",
		1: "ENGINE_CLASS_A",
		2: "ENGINE_CLASS_B",
		3: "ENGINE_CLASS_C",
	}
	EngineClass_value = map[string]int32{
		"ENGINE_CLASS_UNSPECIFIED": 0,
		"ENGINE_CLASS_A":           1,
		"ENGINE_CLASS_B":           2,
		"ENGINE_CLASS_C":           3,
	}
)

func (x EngineClass) Enum() *EngineClass {
	p := new(EngineClass)
	*p = x
	return p
}

func (x EngineClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EngineClass) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_v1_inventory_proto_enumTypes[1].Descriptor()
}

func (EngineClass) Type() protoreflect.EnumType {
	return &file_inventory_v1_inventory_proto_enumTypes[1]
}

func (x EngineClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EngineClass.Descriptor instead.
func (EngineClass) EnumDescriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

// ShieldType тип щита
type ShieldType int32

const (
	// SHIELD_TYPE_UNSPECIFIED не указан
	ShieldType_SHIELD_TYPE_UNSPECIFIED ShieldType = 0
	// SHIELD_TYPE_ENERGY энергетический щит
	ShieldType_SHIELD_TYPE_ENERGY ShieldType = 1
	// SHIELD_TYPE_PLASMA плазменный щит
	ShieldType_SHIELD_TYPE_PLASMA ShieldType = 2
)

// Enum value maps for ShieldType.
var (
	ShieldType_name = map[int32]string{
		0: "SHIELD_TYPE_UNSPECIFIED",
		1: "SHIELD_TYPE_ENERGY",
		2: "SHIELD_TYPE_PLASMA",
	}
	ShieldType_value = map[string]int32{
		"SHIELD_TYPE_UNSPECIFIED": 0,
		"SHIELD_TYPE_ENERGY":      1,
		"SHIELD_TYPE_PLASMA":      2,
	}
)

func (x ShieldType) Enum() *ShieldType {
	p := new(ShieldType)
	*p = x
	return p
}

func (x ShieldType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShieldType) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_v1_inventory_proto_enumTypes[2].Descriptor()
}

func (ShieldType) Type() protoreflect.EnumType {
	return &file_inventory_v1_inventory_proto_enumTypes[2]
}

func (x ShieldType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShieldType.Descriptor instead.
func (ShieldType) EnumDescriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

// WeaponType тип оружия
type WeaponType int32

const (
	// WEAPON_TYPE_UNSPECIFIED не указан
	WeaponType_WEAPON_TYPE_UNSPECIFIED WeaponType = 0
	// WEAPON_TYPE_LASER лазерное оружие
	WeaponType_WEAPON_TYPE_LASER WeaponType = 1
	// WEAPON_TYPE_MISSILE ракетное оружие
	WeaponType_WEAPON_TYPE_MISSILE WeaponType = 2
)

// Enum value maps for WeaponType.
var (
	WeaponType_name = map[int32]string{
		0: "WEAPON_TYPE_UNSPECIFIED",
		1: "WEAPON_TYPE_LASER",
		2: "WEAPON_TYPE_MISSILE",
	}
	WeaponType_value = map[string]int32{
		"WEAPON_TYPE_UNSPECIFIED": 0,
		"WEAPON_TYPE_LASER":       1,
		"WEAPON_TYPE_MISSILE":     2,
	}
)

func (x WeaponType) Enum() *WeaponType {
	p := new(WeaponType)
	*p = x
	return p
}

func (x WeaponType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WeaponType) Descriptor() protoreflect.EnumDescriptor {
	return file_inventory_v1_inventory_proto_enumTypes[3].Descriptor()
}

func (WeaponType) Type() protoreflect.EnumType {
	return &file_inventory_v1_inventory_proto_enumTypes[3]
}

func (x WeaponType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WeaponType.Descriptor instead.
func (WeaponType) EnumDescriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

// Part деталь космического корабля
type Part struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid уникальный идентификатор детали
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// info основная информация о детали
	Info *PartInfo `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	// created_at время создания записи
	CreatedAt *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// updated_at время последнего обновления записи
	UpdatedAt *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	// deleted_at время удаления записи (опционально)
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt,proto3" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Part) Reset() {
	*x = Part{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Part) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Part) ProtoMessage() {}

func (x *Part) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Part.ProtoReflect.Descriptor instead.
func (*Part) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *Part) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Part) GetInfo() *PartInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Part) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Part) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Part) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

// PartProperties типоспецифичные свойства детали. Заполнено ровно одно поле —
// то, что соответствует part_type родительской Part.
type PartProperties struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// properties типоспецифичные свойства детали
	//
	// Types that are valid to be assigned to Properties:
	//
	//	*PartProperties_Hull
	//	*PartProperties_Engine
	//	*PartProperties_Shield
	//	*PartProperties_Weapon
	Properties    isPartProperties_Properties `protobuf_oneof:"properties"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartProperties) Reset() {
	*x = PartProperties{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartProperties) ProtoMessage() {}

func (x *PartProperties) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartProperties.ProtoReflect.Descriptor instead.
func (*PartProperties) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *PartProperties) GetProperties() isPartProperties_Properties {
	if x != nil {
		return x.Properties
	}
	return nil
}

func (x *PartProperties) GetHull() *HullProperties {
	if x != nil {
		if x, ok := x.Properties.(*PartProperties_Hull); ok {
			return x.Hull
		}
	}
	return nil
}

func (x *PartProperties) GetEngine() *EngineProperties {
	if x != nil {
		if x, ok := x.Properties.(*PartProperties_Engine); ok {
			return x.Engine
		}
	}
	return nil
}

func (x *PartProperties) GetShield() *ShieldProperties {
	if x != nil {
		if x, ok := x.Properties.(*PartProperties_Shield); ok {
			return x.Shield
		}
	}
	return nil
}

func (x *PartProperties) GetWeapon() *WeaponProperties {
	if x != nil {
		if x, ok := x.Properties.(*PartProperties_Weapon); ok {
			return x.Weapon
		}
	}
	return nil
}

type isPartProperties_Properties interface {
	isPartProperties_Properties()
}

type PartProperties_Hull struct {
	// hull свойства корпуса
	Hull *HullProperties `protobuf:"bytes,1,opt,name=hull,proto3,oneof"`
}

type PartProperties_Engine struct {
	// engine свойства двигателя
	Engine *EngineProperties `protobuf:"bytes,2,opt,name=engine,proto3,oneof"`
}

type PartProperties_Shield struct {
	// shield свойства щита
	Shield *ShieldProperties `protobuf:"bytes,3,opt,name=shield,proto3,oneof"`
}

type PartProperties_Weapon struct {
	// weapon свойства оружия
	Weapon *WeaponProperties `protobuf:"bytes,4,opt,name=weapon,proto3,oneof"`
}

func (*PartProperties_Hull) isPartProperties_Properties() {}

func (*PartProperties_Engine) isPartProperties_Properties() {}

func (*PartProperties_Shield) isPartProperties_Properties() {}

func (*PartProperties_Weapon) isPartProperties_Properties() {}

// HullProperties свойства корпуса
type HullProperties struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// strength прочность корпуса
	Strength      int64 `protobuf:"varint,1,opt,name=strength,proto3" json:"strength,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HullProperties) Reset() {
	*x = HullProperties{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HullProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HullProperties) ProtoMessage() {}

func (x *HullProperties) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HullProperties.ProtoReflect.Descriptor instead.
func (*HullProperties) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *HullProperties) GetStrength() int64 {
	if x != nil {
		return x.Strength
	}
	return 0
}

// EngineProperties свойства двигателя
type EngineProperties struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// class класс двигателя
	Class EngineClass `protobuf:"varint,1,opt,name=class,proto3,enum=inventory.v1.EngineClass" json:"class,omitempty"`
	// required_strength минимальная прочность корпуса, необходимая для этого двигателя
	RequiredStrength int64 `protobuf:"varint,2,opt,name=required_strength,json=requiredStrength,proto3" json:"required_strength,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *EngineProperties) Reset() {
	*x = EngineProperties{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EngineProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EngineProperties) ProtoMessage() {}

func (x *EngineProperties) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EngineProperties.ProtoReflect.Descriptor instead.
func (*EngineProperties) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *EngineProperties) GetClass() EngineClass {
	if x != nil {
		return x.Class
	}
	return EngineClass_ENGINE_CLASS_UNSPECIFIED
}

func (x *EngineProperties) GetRequiredStrength() int64 {
	if x != nil {
		return x.RequiredStrength
	}
	return 0
}

// ShieldProperties свойства щита
type ShieldProperties struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// shield_type тип щита
	ShieldType    ShieldType `protobuf:"varint,1,opt,name=shield_type,json=shieldType,proto3,enum=inventory.v1.ShieldType" json:"shield_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShieldProperties) Reset() {
	*x = ShieldProperties{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShieldProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShieldProperties) ProtoMessage() {}

func (x *ShieldProperties) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShieldProperties.ProtoReflect.Descriptor instead.
func (*ShieldProperties) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *ShieldProperties) GetShieldType() ShieldType {
	if x != nil {
		return x.ShieldType
	}
	return ShieldType_SHIELD_TYPE_UNSPECIFIED
}

// WeaponProperties свойства оружия
type WeaponProperties struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// weapon_type тип оружия
	WeaponType    WeaponType `protobuf:"varint,1,opt,name=weapon_type,json=weaponType,proto3,enum=inventory.v1.WeaponType" json:"weapon_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WeaponProperties) Reset() {
	*x = WeaponProperties{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WeaponProperties) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WeaponProperties) ProtoMessage() {}

func (x *WeaponProperties) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WeaponProperties.ProtoReflect.Descriptor instead.
func (*WeaponProperties) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *WeaponProperties) GetWeaponType() WeaponType {
	if x != nil {
		return x.WeaponType
	}
	return WeaponType_WEAPON_TYPE_UNSPECIFIED
}

// PartInfo основная информация о детали
type PartInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name название детали
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// description описание детали
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// price цена в копейках (5000₽ = 500000)
	Price int64 `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	// part_type тип детали
	PartType PartType `protobuf:"varint,4,opt,name=part_type,json=partType,proto3,enum=inventory.v1.PartType" json:"part_type,omitempty"`
	// stock_quantity количество на складе
	StockQuantity int64 `protobuf:"varint,5,opt,name=stock_quantity,json=stockQuantity,proto3" json:"stock_quantity,omitempty"`
	// properties типоспецифичные свойства детали (опционально, зависит от part_type)
	Properties    *PartProperties `protobuf:"bytes,6,opt,name=properties,proto3" json:"properties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartInfo) Reset() {
	*x = PartInfo{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartInfo) ProtoMessage() {}

func (x *PartInfo) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartInfo.ProtoReflect.Descriptor instead.
func (*PartInfo) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{6}
}

func (x *PartInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PartInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *PartInfo) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PartInfo) GetPartType() PartType {
	if x != nil {
		return x.PartType
	}
	return PartType_PART_TYPE_UNSPECIFIED
}

func (x *PartInfo) GetStockQuantity() int64 {
	if x != nil {
		return x.StockQuantity
	}
	return 0
}

func (x *PartInfo) GetProperties() *PartProperties {
	if x != nil {
		return x.Properties
	}
	return nil
}

// GetPartRequest запрос на получение детали по UUID
type GetPartRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid уникальный идентификатор детали
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartRequest) Reset() {
	*x = GetPartRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartRequest) ProtoMessage() {}

func (x *GetPartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartRequest.ProtoReflect.Descriptor instead.
func (*GetPartRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{7}
}

func (x *GetPartRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// GetPartResponse ответ на запрос получения детали
type GetPartResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// part деталь космического корабля
	Part          *Part `protobuf:"bytes,1,opt,name=part,proto3" json:"part,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPartResponse) Reset() {
	*x = GetPartResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPartResponse) ProtoMessage() {}

func (x *GetPartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPartResponse.ProtoReflect.Descriptor instead.
func (*GetPartResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{8}
}

func (x *GetPartResponse) GetPart() *Part {
	if x != nil {
		return x.Part
	}
	return nil
}

// DeletePartRequest запрос на удаление детали по UUID
type DeletePartRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid уникальный идентификатор детали
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePartRequest) Reset() {
	*x = DeletePartRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePartRequest) ProtoMessage() {}

func (x *DeletePartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePartRequest.ProtoReflect.Descriptor instead.
func (*DeletePartRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{9}
}

func (x *DeletePartRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// GetAllPartRequest запрос на получение всех деталей
type GetAllPartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPartRequest) Reset() {
	*x = GetAllPartRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPartRequest) ProtoMessage() {}

func (x *GetAllPartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPartRequest.ProtoReflect.Descriptor instead.
func (*GetAllPartRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{10}
}

// GetAllPartResponse ответ со всеми деталями
type GetAllPartResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// part список деталей
	Part []*Part `protobuf:"bytes,1,rep,name=part,proto3" json:"part,omitempty"`
	// total_count общее количество деталей
	TotalCount    int64 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllPartResponse) Reset() {
	*x = GetAllPartResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllPartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllPartResponse) ProtoMessage() {}

func (x *GetAllPartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllPartResponse.ProtoReflect.Descriptor instead.
func (*GetAllPartResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{11}
}

func (x *GetAllPartResponse) GetPart() []*Part {
	if x != nil {
		return x.Part
	}
	return nil
}

func (x *GetAllPartResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// ListPartsRequest запрос на получение списка деталей с фильтрацией
type ListPartsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// filter параметры фильтрации
	Filter        *PartsFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartsRequest) Reset() {
	*x = ListPartsRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartsRequest) ProtoMessage() {}

func (x *ListPartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartsRequest.ProtoReflect.Descriptor instead.
func (*ListPartsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{12}
}

func (x *ListPartsRequest) GetFilter() *PartsFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

// PartsFilter фильтр для поиска деталей
type PartsFilter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuids список UUID для фильтрации
	Uuids []string `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	// part_type список типов деталей для фильтрации
	PartType      []PartType `protobuf:"varint,2,rep,packed,name=part_type,json=partType,proto3,enum=inventory.v1.PartType" json:"part_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartsFilter) Reset() {
	*x = PartsFilter{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartsFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartsFilter) ProtoMessage() {}

func (x *PartsFilter) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartsFilter.ProtoReflect.Descriptor instead.
func (*PartsFilter) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{13}
}

func (x *PartsFilter) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

func (x *PartsFilter) GetPartType() []PartType {
	if x != nil {
		return x.PartType
	}
	return nil
}

// ListPartsResponse ответ со списком деталей
type ListPartsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// part список деталей
	Part []*Part `protobuf:"bytes,1,rep,name=part,proto3" json:"part,omitempty"`
	// total_count общее количество деталей
	TotalCount    int64 `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPartsResponse) Reset() {
	*x = ListPartsResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPartsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPartsResponse) ProtoMessage() {}

func (x *ListPartsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPartsResponse.ProtoReflect.Descriptor instead.
func (*ListPartsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{14}
}

func (x *ListPartsResponse) GetPart() []*Part {
	if x != nil {
		return x.Part
	}
	return nil
}

func (x *ListPartsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

// CreatePartsRequest запрос на создание новой детали
type CreatePartsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// info основная информация о детали
	Info          *PartInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePartsRequest) Reset() {
	*x = CreatePartsRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePartsRequest) ProtoMessage() {}

func (x *CreatePartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePartsRequest.ProtoReflect.Descriptor instead.
func (*CreatePartsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{15}
}

func (x *CreatePartsRequest) GetInfo() *PartInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// CreatePartsResponse ответ на создание детали
type CreatePartsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuid уникальный идентификатор созданной детали
	Uuid          string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePartsResponse) Reset() {
	*x = CreatePartsResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePartsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePartsResponse) ProtoMessage() {}

func (x *CreatePartsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePartsResponse.ProtoReflect.Descriptor instead.
func (*CreatePartsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{16}
}

func (x *CreatePartsResponse) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

// ValidateCompatibilityRequest запрос на проверку совместимости деталей по слотам корабля
type ValidateCompatibilityRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hull_uuid uuid детали в слоте корпуса (обязательный слот)
	HullUuid string `protobuf:"bytes,1,opt,name=hull_uuid,json=hullUuid,proto3" json:"hull_uuid,omitempty"`
	// engine_uuid uuid детали в слоте двигателя (обязательный слот)
	EngineUuid string `protobuf:"bytes,2,opt,name=engine_uuid,json=engineUuid,proto3" json:"engine_uuid,omitempty"`
	// shield_uuid uuid детали в слоте щита (опциональный слот, пустая строка — слот не используется)
	ShieldUuid string `protobuf:"bytes,3,opt,name=shield_uuid,json=shieldUuid,proto3" json:"shield_uuid,omitempty"`
	// weapon_uuid uuid детали в слоте оружия (опциональный слот, пустая строка — слот не используется)
	WeaponUuid    string `protobuf:"bytes,4,opt,name=weapon_uuid,json=weaponUuid,proto3" json:"weapon_uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCompatibilityRequest) Reset() {
	*x = ValidateCompatibilityRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCompatibilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCompatibilityRequest) ProtoMessage() {}

func (x *ValidateCompatibilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCompatibilityRequest.ProtoReflect.Descriptor instead.
func (*ValidateCompatibilityRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{17}
}

func (x *ValidateCompatibilityRequest) GetHullUuid() string {
	if x != nil {
		return x.HullUuid
	}
	return ""
}

func (x *ValidateCompatibilityRequest) GetEngineUuid() string {
	if x != nil {
		return x.EngineUuid
	}
	return ""
}

func (x *ValidateCompatibilityRequest) GetShieldUuid() string {
	if x != nil {
		return x.ShieldUuid
	}
	return ""
}

func (x *ValidateCompatibilityRequest) GetWeaponUuid() string {
	if x != nil {
		return x.WeaponUuid
	}
	return ""
}

// ValidateCompatibilityResponse ответ на проверку совместимости (пустой — значит совместимы)
type ValidateCompatibilityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCompatibilityResponse) Reset() {
	*x = ValidateCompatibilityResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCompatibilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCompatibilityResponse) ProtoMessage() {}

func (x *ValidateCompatibilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCompatibilityResponse.ProtoReflect.Descriptor instead.
func (*ValidateCompatibilityResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{18}
}

// ReservePartsRequest запрос на резервирование деталей
type ReservePartsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuids список uuid деталей для резервирования
	Uuids         []string `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservePartsRequest) Reset() {
	*x = ReservePartsRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservePartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservePartsRequest) ProtoMessage() {}

func (x *ReservePartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservePartsRequest.ProtoReflect.Descriptor instead.
func (*ReservePartsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{19}
}

func (x *ReservePartsRequest) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

// ReservePartsResponse ответ на резервирование (пустой — значит успешно)
type ReservePartsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservePartsResponse) Reset() {
	*x = ReservePartsResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservePartsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservePartsResponse) ProtoMessage() {}

func (x *ReservePartsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservePartsResponse.ProtoReflect.Descriptor instead.
func (*ReservePartsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{20}
}

// ReleasePartsRequest запрос на освобождение ранее зарезервированных деталей
type ReleasePartsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuids список uuid деталей для освобождения
	Uuids         []string `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleasePartsRequest) Reset() {
	*x = ReleasePartsRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleasePartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleasePartsRequest) ProtoMessage() {}

func (x *ReleasePartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleasePartsRequest.ProtoReflect.Descriptor instead.
func (*ReleasePartsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{21}
}

func (x *ReleasePartsRequest) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

// ReleasePartsResponse ответ на освобождение (пустой — значит успешно)
type ReleasePartsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleasePartsResponse) Reset() {
	*x = ReleasePartsResponse{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleasePartsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleasePartsResponse) ProtoMessage() {}

func (x *ReleasePartsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleasePartsResponse.ProtoReflect.Descriptor instead.
func (*ReleasePartsResponse) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{22}
}

// CommitPartsRequest запрос на списание зарезервированных деталей со склада
type CommitPartsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// uuids список uuid деталей для списания
	Uuids         []string `protobuf:"bytes,1,rep,name=uuids,proto3" json:"uuids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitPartsRequest) Reset() {
	*x = CommitPartsRequest{}
	mi := &file_inventory_v1_inventory_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitPartsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitPartsRequest) ProtoMessage() {}

func (x *CommitPartsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inventory_v1_inventory_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitPartsRequest.ProtoReflect.Descriptor instead.
func (*CommitPartsRequest) Descriptor() ([]byte, []int) {
	return file_inventory_v1_inventory_proto_rawDescGZIP(), []int{23}
}

func (x *CommitPartsRequest) GetUuids() []string {
	if x != nil {
		return x.Uuids
	}
	return nil
}

var File_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\x1cinventory/v1/inventory.proto\x12\finventory.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xf7\x01\n" +
	"\x04Part\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12*\n" +
	"\x04info\x18\x02 \x01(\v2\x16.inventory.v1.PartInfoR\x04info\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\"\x80\x02\n" +
	"\x0ePartProperties\x122\n" +
	"\x04hull\x18\x01 \x01(\v2\x1c.inventory.v1.HullPropertiesH\x00R\x04hull\x128\n" +
	"\x06engine\x18\x02 \x01(\v2\x1e.inventory.v1.EnginePropertiesH\x00R\x06engine\x128\n" +
	"\x06shield\x18\x03 \x01(\v2\x1e.inventory.v1.ShieldPropertiesH\x00R\x06shield\x128\n" +
	"\x06weapon\x18\x04 \x01(\v2\x1e.inventory.v1.WeaponPropertiesH\x00R\x06weaponB\f\n" +
	"\n" +
	"properties\",\n" +
	"\x0eHullProperties\x12\x1a\n" +
	"\bstrength\x18\x01 \x01(\x03R\bstrength\"p\n" +
	"\x10EngineProperties\x12/\n" +
	"\x05class\x18\x01 \x01(\x0e2\x19.inventory.v1.EngineClassR\x05class\x12+\n" +
	"\x11required_strength\x18\x02 \x01(\x03R\x10requiredStrength\"M\n" +
	"\x10ShieldProperties\x129\n" +
	"\vshield_type\x18\x01 \x01(\x0e2\x18.inventory.v1.ShieldTypeR\n" +
	"shieldType\"M\n" +
	"\x10WeaponProperties\x129\n" +
	"\vweapon_type\x18\x01 \x01(\x0e2\x18.inventory.v1.WeaponTypeR\n" +
	"weaponType\"\xfb\x01\n" +
	"\bPartInfo\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x182R\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x03R\x05price\x123\n" +
	"\tpart_type\x18\x04 \x01(\x0e2\x16.inventory.v1.PartTypeR\bpartType\x12%\n" +
	"\x0estock_quantity\x18\x05 \x01(\x03R\rstockQuantity\x12<\n" +
	"\n" +
	"properties\x18\x06 \x01(\v2\x1c.inventory.v1.PartPropertiesR\n" +
	"properties\".\n" +
	"\x0eGetPartRequest\x12\x1c\n" +
	"\x04uuid\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x04uuid\"9\n" +
	"\x0fGetPartResponse\x12&\n" +
	"\x04part\x18\x01 \x01(\v2\x12.inventory.v1.PartR\x04part\"1\n" +
	"\x11DeletePartRequest\x12\x1c\n" +
	"\x04uuid\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x04uuid\"\x13\n" +
	"\x11GetAllPartRequest\"]\n" +
	"\x12GetAllPartResponse\x12&\n" +
	"\x04part\x18\x01 \x03(\v2\x12.inventory.v1.PartR\x04part\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"E\n" +
	"\x10ListPartsRequest\x121\n" +
	"\x06filter\x18\x01 \x01(\v2\x19.inventory.v1.PartsFilterR\x06filter\"X\n" +
	"\vPartsFilter\x12\x14\n" +
	"\x05uuids\x18\x01 \x03(\tR\x05uuids\x123\n" +
	"\tpart_type\x18\x02 \x03(\x0e2\x16.inventory.v1.PartTypeR\bpartType\"\\\n" +
	"\x11ListPartsResponse\x12&\n" +
	"\x04part\x18\x01 \x03(\v2\x12.inventory.v1.PartR\x04part\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"@\n" +
	"\x12CreatePartsRequest\x12*\n" +
	"\x04info\x18\x01 \x01(\v2\x16.inventory.v1.PartInfoR\x04info\")\n" +
	"\x13CreatePartsResponse\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\x9e\x01\n" +
	"\x1cValidateCompatibilityRequest\x12\x1b\n" +
	"\thull_uuid\x18\x01 \x01(\tR\bhullUuid\x12\x1f\n" +
	"\vengine_uuid\x18\x02 \x01(\tR\n" +
	"engineUuid\x12\x1f\n" +
	"\vshield_uuid\x18\x03 \x01(\tR\n" +
	"shieldUuid\x12\x1f\n" +
	"\vweapon_uuid\x18\x04 \x01(\tR\n" +
	"weaponUuid\"\x1f\n" +
	"\x1dValidateCompatibilityResponse\"+\n" +
	"\x13ReservePartsRequest\x12\x14\n" +
	"\x05uuids\x18\x01 \x03(\tR\x05uuids\"\x16\n" +
	"\x14ReservePartsResponse\"+\n" +
	"\x13ReleasePartsRequest\x12\x14\n" +
	"\x05uuids\x18\x01 \x03(\tR\x05uuids\"\x16\n" +
	"\x14ReleasePartsResponse\"*\n" +
	"\x12CommitPartsRequest\x12\x14\n" +
	"\x05uuids\x18\x01 \x03(\tR\x05uuids*{\n" +
	"\bPartType\x12\x19\n" +
	"\x15PART_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0ePART_TYPE_HULL\x10\x01\x12\x14\n" +
	"\x10PART_TYPE_ENGINE\x10\x02\x12\x14\n" +
	"\x10PART_TYPE_SHIELD\x10\x03\x12\x14\n" +
	"\x10PART_TYPE_WEAPON\x10\x04*g\n" +
	"\vEngineClass\x12\x1c\n" +
	"\x18ENGINE_CLASS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eENGINE_CLASS_A\x10\x01\x12\x12\n" +
	"\x0eENGINE_CLASS_B\x10\x02\x12\x12\n" +
	"\x0eENGINE_CLASS_C\x10\x03*Y\n" +
	"\n" +
	"ShieldType\x12\x1b\n" +
	"\x17SHIELD_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12SHIELD_TYPE_ENERGY\x10\x01\x12\x16\n" +
	"\x12SHIELD_TYPE_PLASMA\x10\x02*Y\n" +
	"\n" +
	"WeaponType\x12\x1b\n" +
	"\x17WEAPON_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11WEAPON_TYPE_LASER\x10\x01\x12\x17\n" +
	"\x13WEAPON_TYPE_MISSILE\x10\x022\x97\a\n" +
	"\x10InventoryService\x12h\n" +
	"\aGetPart\x12\x1c.inventory.v1.GetPartRequest\x1a\x1d.inventory.v1.GetPartResponse\" \x82\xd3\xe4\x93\x02\x1a\x12\x18/api/v1/inventory/{uuid}\x12g\n" +
	"\tListParts\x12\x1e.inventory.v1.ListPartsRequest\x1a\x1f.inventory.v1.ListPartsResponse\"\x19\x82\xd3\xe4\x93\x02\x13\x12\x11/api/v1/inventory\x12p\n" +
	"\vCreateParts\x12 .inventory.v1.CreatePartsRequest\x1a!.inventory.v1.CreatePartsResponse\"\x1c\x82\xd3\xe4\x93\x02\x16:\x01*\"\x11/api/v1/inventory\x12l\n" +
	"\n" +
	"GetAllPart\x12\x1f.inventory.v1.GetAllPartRequest\x1a .inventory.v1.GetAllPartResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/inventories\x12g\n" +
	"\n" +
	"DeletePart\x12\x1f.inventory.v1.DeletePartRequest\x1a\x16.google.protobuf.Empty\" \x82\xd3\xe4\x93\x02\x1a*\x18/api/v1/inventory/{uuid}\x12p\n" +
	"\x15ValidateCompatibility\x12*.inventory.v1.ValidateCompatibilityRequest\x1a+.inventory.v1.ValidateCompatibilityResponse\x12U\n" +
	"\fReserveParts\x12!.inventory.v1.ReservePartsRequest\x1a\".inventory.v1.ReservePartsResponse\x12U\n" +
	"\fReleaseParts\x12!.inventory.v1.ReleasePartsRequest\x1a\".inventory.v1.ReleasePartsResponse\x12G\n" +
	"\vCommitParts\x12 .inventory.v1.CommitPartsRequest\x1a\x16.google.protobuf.EmptyBTZRgithub.com/mbakhodurov/homeworks2/week7/shared/pkg/proto/inventory/v1;inventory_v1b\x06proto3"

var (
	file_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_inventory_v1_inventory_proto_rawDescData []byte
)

func file_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_inventory_v1_inventory_proto_rawDescData
}

var file_inventory_v1_inventory_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_inventory_v1_inventory_proto_goTypes = []any{
	(PartType)(0),                         // 0: inventory.v1.PartType
	(EngineClass)(0),                      // 1: inventory.v1.EngineClass
	(ShieldType)(0),                       // 2: inventory.v1.ShieldType
	(WeaponType)(0),                       // 3: inventory.v1.WeaponType
	(*Part)(nil),                          // 4: inventory.v1.Part
	(*PartProperties)(nil),                // 5: inventory.v1.PartProperties
	(*HullProperties)(nil),                // 6: inventory.v1.HullProperties
	(*EngineProperties)(nil),              // 7: inventory.v1.EngineProperties
	(*ShieldProperties)(nil),              // 8: inventory.v1.ShieldProperties
	(*WeaponProperties)(nil),              // 9: inventory.v1.WeaponProperties
	(*PartInfo)(nil),                      // 10: inventory.v1.PartInfo
	(*GetPartRequest)(nil),                // 11: inventory.v1.GetPartRequest
	(*GetPartResponse)(nil),               // 12: inventory.v1.GetPartResponse
	(*DeletePartRequest)(nil),             // 13: inventory.v1.DeletePartRequest
	(*GetAllPartRequest)(nil),             // 14: inventory.v1.GetAllPartRequest
	(*GetAllPartResponse)(nil),            // 15: inventory.v1.GetAllPartResponse
	(*ListPartsRequest)(nil),              // 16: inventory.v1.ListPartsRequest
	(*PartsFilter)(nil),                   // 17: inventory.v1.PartsFilter
	(*ListPartsResponse)(nil),             // 18: inventory.v1.ListPartsResponse
	(*CreatePartsRequest)(nil),            // 19: inventory.v1.CreatePartsRequest
	(*CreatePartsResponse)(nil),           // 20: inventory.v1.CreatePartsResponse
	(*ValidateCompatibilityRequest)(nil),  // 21: inventory.v1.ValidateCompatibilityRequest
	(*ValidateCompatibilityResponse)(nil), // 22: inventory.v1.ValidateCompatibilityResponse
	(*ReservePartsRequest)(nil),           // 23: inventory.v1.ReservePartsRequest
	(*ReservePartsResponse)(nil),          // 24: inventory.v1.ReservePartsResponse
	(*ReleasePartsRequest)(nil),           // 25: inventory.v1.ReleasePartsRequest
	(*ReleasePartsResponse)(nil),          // 26: inventory.v1.ReleasePartsResponse
	(*CommitPartsRequest)(nil),            // 27: inventory.v1.CommitPartsRequest
	(*timestamppb.Timestamp)(nil),         // 28: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                 // 29: google.protobuf.Empty
}
var file_inventory_v1_inventory_proto_depIdxs = []int32{
	10, // 0: inventory.v1.Part.info:type_name -> inventory.v1.PartInfo
	28, // 1: inventory.v1.Part.created_at:type_name -> google.protobuf.Timestamp
	28, // 2: inventory.v1.Part.updated_at:type_name -> google.protobuf.Timestamp
	28, // 3: inventory.v1.Part.deleted_at:type_name -> google.protobuf.Timestamp
	6,  // 4: inventory.v1.PartProperties.hull:type_name -> inventory.v1.HullProperties
	7,  // 5: inventory.v1.PartProperties.engine:type_name -> inventory.v1.EngineProperties
	8,  // 6: inventory.v1.PartProperties.shield:type_name -> inventory.v1.ShieldProperties
	9,  // 7: inventory.v1.PartProperties.weapon:type_name -> inventory.v1.WeaponProperties
	1,  // 8: inventory.v1.EngineProperties.class:type_name -> inventory.v1.EngineClass
	2,  // 9: inventory.v1.ShieldProperties.shield_type:type_name -> inventory.v1.ShieldType
	3,  // 10: inventory.v1.WeaponProperties.weapon_type:type_name -> inventory.v1.WeaponType
	0,  // 11: inventory.v1.PartInfo.part_type:type_name -> inventory.v1.PartType
	5,  // 12: inventory.v1.PartInfo.properties:type_name -> inventory.v1.PartProperties
	4,  // 13: inventory.v1.GetPartResponse.part:type_name -> inventory.v1.Part
	4,  // 14: inventory.v1.GetAllPartResponse.part:type_name -> inventory.v1.Part
	17, // 15: inventory.v1.ListPartsRequest.filter:type_name -> inventory.v1.PartsFilter
	0,  // 16: inventory.v1.PartsFilter.part_type:type_name -> inventory.v1.PartType
	4,  // 17: inventory.v1.ListPartsResponse.part:type_name -> inventory.v1.Part
	10, // 18: inventory.v1.CreatePartsRequest.info:type_name -> inventory.v1.PartInfo
	11, // 19: inventory.v1.InventoryService.GetPart:input_type -> inventory.v1.GetPartRequest
	16, // 20: inventory.v1.InventoryService.ListParts:input_type -> inventory.v1.ListPartsRequest
	19, // 21: inventory.v1.InventoryService.CreateParts:input_type -> inventory.v1.CreatePartsRequest
	14, // 22: inventory.v1.InventoryService.GetAllPart:input_type -> inventory.v1.GetAllPartRequest
	13, // 23: inventory.v1.InventoryService.DeletePart:input_type -> inventory.v1.DeletePartRequest
	21, // 24: inventory.v1.InventoryService.ValidateCompatibility:input_type -> inventory.v1.ValidateCompatibilityRequest
	23, // 25: inventory.v1.InventoryService.ReserveParts:input_type -> inventory.v1.ReservePartsRequest
	25, // 26: inventory.v1.InventoryService.ReleaseParts:input_type -> inventory.v1.ReleasePartsRequest
	27, // 27: inventory.v1.InventoryService.CommitParts:input_type -> inventory.v1.CommitPartsRequest
	12, // 28: inventory.v1.InventoryService.GetPart:output_type -> inventory.v1.GetPartResponse
	18, // 29: inventory.v1.InventoryService.ListParts:output_type -> inventory.v1.ListPartsResponse
	20, // 30: inventory.v1.InventoryService.CreateParts:output_type -> inventory.v1.CreatePartsResponse
	15, // 31: inventory.v1.InventoryService.GetAllPart:output_type -> inventory.v1.GetAllPartResponse
	29, // 32: inventory.v1.InventoryService.DeletePart:output_type -> google.protobuf.Empty
	22, // 33: inventory.v1.InventoryService.ValidateCompatibility:output_type -> inventory.v1.ValidateCompatibilityResponse
	24, // 34: inventory.v1.InventoryService.ReserveParts:output_type -> inventory.v1.ReservePartsResponse
	26, // 35: inventory.v1.InventoryService.ReleaseParts:output_type -> inventory.v1.ReleasePartsResponse
	29, // 36: inventory.v1.InventoryService.CommitParts:output_type -> google.protobuf.Empty
	28, // [28:37] is the sub-list for method output_type
	19, // [19:28] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_inventory_v1_inventory_proto_init() }
func file_inventory_v1_inventory_proto_init() {
	if File_inventory_v1_inventory_proto != nil {
		return
	}
	file_inventory_v1_inventory_proto_msgTypes[1].OneofWrappers = []any{
		(*PartProperties_Hull)(nil),
		(*PartProperties_Engine)(nil),
		(*PartProperties_Shield)(nil),
		(*PartProperties_Weapon)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inventory_v1_inventory_proto_rawDesc), len(file_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_inventory_v1_inventory_proto_depIdxs,
		EnumInfos:         file_inventory_v1_inventory_proto_enumTypes,
		MessageInfos:      file_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_inventory_v1_inventory_proto = out.File
	file_inventory_v1_inventory_proto_goTypes = nil
	file_inventory_v1_inventory_proto_depIdxs = nil
}
